server:
  port: 17173
  servlet:
    path: /demo

spring:
  aop:
    auto: true

  redis:
    database: 0
    timeout: 60000ms
    jedis:
      pool:
        max-idle: 8
        max-wait: 60000ms
        min-idle: 0
        max-active: 200
    cluster:
      password: crmredis
      max-attempts: 5
      so-timeout: 2000
      connection-timeout: 2000
      max-redirects: 5
      nodes: 192.168.10.187:7001,192.168.10.188:7002,192.168.10.189:7003,192.168.10.187:7004,192.168.10.188:7005,192.168.10.189:7006
    # 连接内部用户 redis 使用 URI的redis连接
    url: redis://djredis:djredis@192.168.10.173:6379/5

   # datasource 数据源配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.23.14:8066/crm?useUnicode=true&autoReconnect=true&amp;characterEncoding=UTF8&allowMultiQueries=true
    username: djcrm
    password: dongjingcrm
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    type: com.alibaba.druid.pool.DruidDataSource

    #连接池
    initialSize: 5
    min-idle: 5
    max-active: 20
    max-wait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL


  #rabbit 配置
  rabbitmq:
    port: 5672
    host: 192.168.10.185
    username: xiaoqian
    password: xiaoqian
    publisher-confirms: true #支持发布确认
    publisher-returns: true  #支持发布返回
    listener:
      simple:
        acknowledge-mode: manual #采用手动应答
        concurrency: 1 #指定最小的消费者数量
        max-concurrency: 1 #指定最大的消费者数量
        retry:
          enabled: true #是否支持重试


mybatis:
  #实体类所做包
  type-aliases-package: com.djcps.boot.modules.*.model
  #mapper.xml所在位置
  mapper-locations: classpath:mapper/**/*Mapper.xml
  config-location: classpath:mybatis-config.xml


#日志
logging:
  config: classpath:log4j2.xml

---
